### ISSUE TITLE
`tgif_sample_negative` function call in negative sampling

### ISSUE THREAD

**Issue by Zrealshadow** [awslabs/multi-table-benchmark#4]
Hi, thx for sharing the solid work. 

I'm learning the source code.

I'm confused about the source code in `base_gml_solution.py` about the negative sampling step.

I can not find any document about the method `tgif_sample_negative`.  

The `datapipe` is a class of `ItemSampler`. 

I searched in the DGL document from version 2.1.x to 2.3.x, seems there is no doc about this function.

https://github.com/awslabs/multi-table-benchmark/blob/198e437e79f1b85321c26217bd179c56b9774e94/dbinfer/solutions/base_gml_solution.py#L250-L259

**Comment by BarclayII** [comment]
The `tgif_sample_negative` DataPipe is defined in
https://github.com/awslabs/multi-table-benchmark/blob/198e437e79f1b85321c26217bd179c56b9774e94/dbinfer/solutions/negative_sampler.py#L25-L26

**Comment by Zrealshadow** [comment]
thx
